<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="1" total="6" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="21466" started-at="2020-07-19T11:10:35Z" finished-at="2020-07-19T11:10:56Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="21466" started-at="2020-07-19T11:10:35Z" finished-at="2020-07-19T11:10:56Z">
      <class name="org.test4.Rerun">
        <test-method status="PASS" signature="launch()[pri:0, instance:org.test4.Rerun@42d80b78]" name="launch" is-config="true" duration-ms="12172" started-at="2020-07-19T16:40:35Z" finished-at="2020-07-19T16:40:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method status="PASS" signature="start()[pri:0, instance:org.test4.Rerun@42d80b78]" name="start" is-config="true" duration-ms="63" started-at="2020-07-19T16:40:47Z" finished-at="2020-07-19T16:40:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="SKIP" signature="check()[pri:0, instance:org.test4.Rerun@42d80b78]" name="check" duration-ms="48" started-at="2020-07-19T16:40:47Z" finished-at="2020-07-19T16:40:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at org.test4.Rerun.check(Rerun.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- check -->
        <test-method status="PASS" signature="ending()[pri:0, instance:org.test4.Rerun@42d80b78]" name="ending" is-config="true" duration-ms="1" started-at="2020-07-19T16:40:47Z" finished-at="2020-07-19T16:40:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ending -->
        <test-method status="PASS" signature="start()[pri:0, instance:org.test4.Rerun@42d80b78]" name="start" is-config="true" duration-ms="4" started-at="2020-07-19T16:40:47Z" finished-at="2020-07-19T16:40:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="SKIP" signature="check()[pri:0, instance:org.test4.Rerun@42d80b78]" name="check" duration-ms="7" started-at="2020-07-19T16:40:47Z" finished-at="2020-07-19T16:40:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at org.test4.Rerun.check(Rerun.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:958)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- check -->
        <test-method status="PASS" signature="ending()[pri:0, instance:org.test4.Rerun@42d80b78]" name="ending" is-config="true" duration-ms="0" started-at="2020-07-19T16:40:47Z" finished-at="2020-07-19T16:40:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ending -->
        <test-method status="PASS" signature="start()[pri:0, instance:org.test4.Rerun@42d80b78]" name="start" is-config="true" duration-ms="0" started-at="2020-07-19T16:40:47Z" finished-at="2020-07-19T16:40:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="SKIP" signature="check()[pri:0, instance:org.test4.Rerun@42d80b78]" name="check" duration-ms="9" started-at="2020-07-19T16:40:47Z" finished-at="2020-07-19T16:40:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at org.test4.Rerun.check(Rerun.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:958)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- check -->
        <test-method status="PASS" signature="start()[pri:0, instance:org.test4.Rerun@42d80b78]" name="start" is-config="true" duration-ms="4" started-at="2020-07-19T16:40:47Z" finished-at="2020-07-19T16:40:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="PASS" signature="ending()[pri:0, instance:org.test4.Rerun@42d80b78]" name="ending" is-config="true" duration-ms="0" started-at="2020-07-19T16:40:47Z" finished-at="2020-07-19T16:40:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ending -->
        <test-method status="FAIL" signature="check()[pri:0, instance:org.test4.Rerun@42d80b78]" name="check" duration-ms="12" started-at="2020-07-19T16:40:47Z" finished-at="2020-07-19T16:40:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at org.test4.Rerun.check(Rerun.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:958)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- check -->
        <test-method status="PASS" signature="ending()[pri:0, instance:org.test4.Rerun@42d80b78]" name="ending" is-config="true" duration-ms="0" started-at="2020-07-19T16:40:47Z" finished-at="2020-07-19T16:40:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ending -->
        <test-method status="PASS" signature="start()[pri:0, instance:org.test4.Rerun@42d80b78]" name="start" is-config="true" duration-ms="4" started-at="2020-07-19T16:40:47Z" finished-at="2020-07-19T16:40:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="PASS" signature="ending()[pri:0, instance:org.test4.Rerun@42d80b78]" name="ending" duration-ms="8" started-at="2020-07-19T16:40:47Z" finished-at="2020-07-19T16:40:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ending -->
        <test-method status="PASS" signature="ending()[pri:0, instance:org.test4.Rerun@42d80b78]" name="ending" is-config="true" duration-ms="6" started-at="2020-07-19T16:40:47Z" finished-at="2020-07-19T16:40:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ending -->
        <test-method status="PASS" signature="start()[pri:0, instance:org.test4.Rerun@42d80b78]" name="start" is-config="true" duration-ms="0" started-at="2020-07-19T16:40:47Z" finished-at="2020-07-19T16:40:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="PASS" signature="table()[pri:0, instance:org.test4.Rerun@42d80b78]" name="table" duration-ms="8972" started-at="2020-07-19T16:40:47Z" finished-at="2020-07-19T16:40:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- table -->
        <test-method status="PASS" signature="ending()[pri:0, instance:org.test4.Rerun@42d80b78]" name="ending" is-config="true" duration-ms="0" started-at="2020-07-19T16:40:56Z" finished-at="2020-07-19T16:40:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ending -->
        <test-method status="PASS" signature="end()[pri:0, instance:org.test4.Rerun@42d80b78]" name="end" is-config="true" duration-ms="1" started-at="2020-07-19T16:40:56Z" finished-at="2020-07-19T16:40:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
      </class> <!-- org.test4.Rerun -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
